name: Release to @pr-<number> tag on npm

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  release-pr:
    name: "Release PR to npm"
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: CI Setup
        uses: ./.github/actions/ci-setup

      - name: Ensure NPM access
        run: npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Get PR version
        id: pr_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          PR_VERSION="${VERSION}-pr${{ github.event.pull_request.number }}-${TIMESTAMP}"
          echo "PR version: $PR_VERSION"
          echo "::set-output name=pr_version::$PR_VERSION"

      - name: Publish PR package with tag
        run: |
          npm version --no-git-tag-version ${{ steps.pr_version.outputs.pr_version }}
          npm publish --tag pr-${{ github.event.pull_request.number }}

        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - uses: mshick/add-pr-comment@v2
        with:
          message: |
            This PR is published in NPM with version **${{ steps.pr_version.outputs.pr_version }}**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
